
server:
  port: 8770
spring:
  application:
    name: server-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8766/eureka/
feign:
  hystrix:
    enabled: true
#feign.hystrix.enabled=true